#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    previousPosition = 0
    currentPosition = 0;
    valleys = 0;

    for i in s:
        previousPosition = currentPosition
        if i == "D":
            currentPosition -= 1
        else:
            currentPosition += 1
        
        if currentPosition < 0 and previousPosition == 0:
            valleys += 1

    return valleys

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
