#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):

    odds = []
    pair = False
    remove = 0
    pairs = 0

    for i in ar:
        for j in range(len(odds)):
            if i == odds[j]:
                pair = True
                remove = j
        if pair:
            odds.pop(remove)
            pairs += 1
            pair = False
        else:
            odds.append(int(i))

    print(pairs)
    return pairs

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
